name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.chestpreview.ChestPreview

author: hexosse
website: www.github.hexosse

depend: []
softdepend: [Multiverse-Core]

permissions:
  ChestPreview.admin: {description: Allows creation of chest preview to admin users, default: false}
  ChestPreview.*:
    default: op
    children:
        ChestPreview.admin: true
